# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-11.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/karimnaaji/Documents/programmation/projets/hdr_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/karimnaaji/Documents/programmation/projets/hdr_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-11.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/karimnaaji/Documents/programmation/projets/hdr_project/CMakeFiles /Users/karimnaaji/Documents/programmation/projets/hdr_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/karimnaaji/Documents/programmation/projets/hdr_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build/hdr.out

# Build rule for target.
build/hdr.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build/hdr.out
.PHONY : build/hdr.out

# fast build rule for target.
build/hdr.out/fast:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/build
.PHONY : build/hdr.out/fast

#=============================================================================
# Target rules for targets named c_lib

# Build rule for target.
c_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c_lib
.PHONY : c_lib

# fast build rule for target.
c_lib/fast:
	$(MAKE) -f CMakeFiles/c_lib.dir/build.make CMakeFiles/c_lib.dir/build
.PHONY : c_lib/fast

lib/rgbe.o: lib/rgbe.c.o
.PHONY : lib/rgbe.o

# target to build an object file
lib/rgbe.c.o:
	$(MAKE) -f CMakeFiles/c_lib.dir/build.make CMakeFiles/c_lib.dir/lib/rgbe.c.o
.PHONY : lib/rgbe.c.o

lib/rgbe.i: lib/rgbe.c.i
.PHONY : lib/rgbe.i

# target to preprocess a source file
lib/rgbe.c.i:
	$(MAKE) -f CMakeFiles/c_lib.dir/build.make CMakeFiles/c_lib.dir/lib/rgbe.c.i
.PHONY : lib/rgbe.c.i

lib/rgbe.s: lib/rgbe.c.s
.PHONY : lib/rgbe.s

# target to generate assembly for a file
lib/rgbe.c.s:
	$(MAKE) -f CMakeFiles/c_lib.dir/build.make CMakeFiles/c_lib.dir/lib/rgbe.c.s
.PHONY : lib/rgbe.c.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/core/geometry.o: src/core/geometry.cpp.o
.PHONY : src/core/geometry.o

# target to build an object file
src/core/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/geometry.cpp.o
.PHONY : src/core/geometry.cpp.o

src/core/geometry.i: src/core/geometry.cpp.i
.PHONY : src/core/geometry.i

# target to preprocess a source file
src/core/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/geometry.cpp.i
.PHONY : src/core/geometry.cpp.i

src/core/geometry.s: src/core/geometry.cpp.s
.PHONY : src/core/geometry.s

# target to generate assembly for a file
src/core/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/geometry.cpp.s
.PHONY : src/core/geometry.cpp.s

src/core/material.o: src/core/material.cpp.o
.PHONY : src/core/material.o

# target to build an object file
src/core/material.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/material.cpp.o
.PHONY : src/core/material.cpp.o

src/core/material.i: src/core/material.cpp.i
.PHONY : src/core/material.i

# target to preprocess a source file
src/core/material.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/material.cpp.i
.PHONY : src/core/material.cpp.i

src/core/material.s: src/core/material.cpp.s
.PHONY : src/core/material.s

# target to generate assembly for a file
src/core/material.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/material.cpp.s
.PHONY : src/core/material.cpp.s

src/core/mesh.o: src/core/mesh.cpp.o
.PHONY : src/core/mesh.o

# target to build an object file
src/core/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/mesh.cpp.o
.PHONY : src/core/mesh.cpp.o

src/core/mesh.i: src/core/mesh.cpp.i
.PHONY : src/core/mesh.i

# target to preprocess a source file
src/core/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/mesh.cpp.i
.PHONY : src/core/mesh.cpp.i

src/core/mesh.s: src/core/mesh.cpp.s
.PHONY : src/core/mesh.s

# target to generate assembly for a file
src/core/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/core/mesh.cpp.s
.PHONY : src/core/mesh.cpp.s

src/hdr/hdrcubemap.o: src/hdr/hdrcubemap.cpp.o
.PHONY : src/hdr/hdrcubemap.o

# target to build an object file
src/hdr/hdrcubemap.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/hdr/hdrcubemap.cpp.o
.PHONY : src/hdr/hdrcubemap.cpp.o

src/hdr/hdrcubemap.i: src/hdr/hdrcubemap.cpp.i
.PHONY : src/hdr/hdrcubemap.i

# target to preprocess a source file
src/hdr/hdrcubemap.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/hdr/hdrcubemap.cpp.i
.PHONY : src/hdr/hdrcubemap.cpp.i

src/hdr/hdrcubemap.s: src/hdr/hdrcubemap.cpp.s
.PHONY : src/hdr/hdrcubemap.s

# target to generate assembly for a file
src/hdr/hdrcubemap.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/hdr/hdrcubemap.cpp.s
.PHONY : src/hdr/hdrcubemap.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objects/camera.o: src/objects/camera.cpp.o
.PHONY : src/objects/camera.o

# target to build an object file
src/objects/camera.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/objects/camera.cpp.o
.PHONY : src/objects/camera.cpp.o

src/objects/camera.i: src/objects/camera.cpp.i
.PHONY : src/objects/camera.i

# target to preprocess a source file
src/objects/camera.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/objects/camera.cpp.i
.PHONY : src/objects/camera.cpp.i

src/objects/camera.s: src/objects/camera.cpp.s
.PHONY : src/objects/camera.s

# target to generate assembly for a file
src/objects/camera.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/objects/camera.cpp.s
.PHONY : src/objects/camera.cpp.s

src/render/renderer.o: src/render/renderer.cpp.o
.PHONY : src/render/renderer.o

# target to build an object file
src/render/renderer.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/render/renderer.cpp.o
.PHONY : src/render/renderer.cpp.o

src/render/renderer.i: src/render/renderer.cpp.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/render/renderer.cpp.i
.PHONY : src/render/renderer.cpp.i

src/render/renderer.s: src/render/renderer.cpp.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/render/renderer.cpp.s
.PHONY : src/render/renderer.cpp.s

src/render/shader.o: src/render/shader.cpp.o
.PHONY : src/render/shader.o

# target to build an object file
src/render/shader.cpp.o:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/render/shader.cpp.o
.PHONY : src/render/shader.cpp.o

src/render/shader.i: src/render/shader.cpp.i
.PHONY : src/render/shader.i

# target to preprocess a source file
src/render/shader.cpp.i:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/render/shader.cpp.i
.PHONY : src/render/shader.cpp.i

src/render/shader.s: src/render/shader.cpp.s
.PHONY : src/render/shader.s

# target to generate assembly for a file
src/render/shader.cpp.s:
	$(MAKE) -f CMakeFiles/build/hdr.out.dir/build.make CMakeFiles/build/hdr.out.dir/src/render/shader.cpp.s
.PHONY : src/render/shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... build/hdr.out"
	@echo "... c_lib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lib/rgbe.o"
	@echo "... lib/rgbe.i"
	@echo "... lib/rgbe.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/core/geometry.o"
	@echo "... src/core/geometry.i"
	@echo "... src/core/geometry.s"
	@echo "... src/core/material.o"
	@echo "... src/core/material.i"
	@echo "... src/core/material.s"
	@echo "... src/core/mesh.o"
	@echo "... src/core/mesh.i"
	@echo "... src/core/mesh.s"
	@echo "... src/hdr/hdrcubemap.o"
	@echo "... src/hdr/hdrcubemap.i"
	@echo "... src/hdr/hdrcubemap.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objects/camera.o"
	@echo "... src/objects/camera.i"
	@echo "... src/objects/camera.s"
	@echo "... src/render/renderer.o"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... src/render/shader.o"
	@echo "... src/render/shader.i"
	@echo "... src/render/shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

